const DARKMODEBACKGROUNDCOLOR  = '#272625';
const LIGHTMODEBACKGROUNDCOLOR = '#FAF9F6';
const LIGHTMODECONTINERCOLOR = '#fff';
const DARKMODECONTINERCOLOR  = '#000'
const LIGHTMODEFOOTERCOLOR = 'orange'
const DARKMODEFOOTERCOLOR = '#272625';
const LIGHTMODEBUTTONCOLOR = 'orange'
const DARKMODEBUTTONCOLOR = '#333';
const LIGHTMODETEXTCOLOR = '#333'
const DARKMODETEXTCOLOR = '#fff'

const light = {
  BACKGROUND: LIGHTMODEBACKGROUNDCOLOR,
  FOOTER: LIGHTMODEFOOTERCOLOR,
  BUTTON:LIGHTMODEBUTTONCOLOR,
  TEXT: LIGHTMODETEXTCOLOR,
  CONTAINER:LIGHTMODECONTINERCOLOR
};

const dark = {
  BACKGROUND: DARKMODEBACKGROUNDCOLOR,
  FOOTER: DARKMODEFOOTERCOLOR,
  BUTTON:DARKMODEBUTTONCOLOR,
  TEXT: DARKMODETEXTCOLOR,
  CONTAINER:DARKMODECONTINERCOLOR
};

export { dark, light };
